### ISSUE TITLE
tql<script>alert('XSS test')</script>

### ISSUE THREAD

**Issue by kidultff** [Yu-Tu/security_tools#1]
worship big old!!!!

---------------------------------------------------------

<script>alert('XSS test')</script>
### <script>alert('XSS test')</script>
**<script>alert('XSS test')</script>**
_<script>alert('XSS test')</script>_
<script>alert('XSS test')</script>

- <script>alert('XSS test')</script>

- [ ] <script>alert('XSS test')</script>

**Comment by Yu-Tu** [comment]
You are so bad!
